# Generated by Django 4.2.5 on 2023-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactprofile_subject_portfolio_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subject'),
        ),
    ]
